"""
Language translation support for Hindi and Marathi
"""

TRANSLATIONS = {
    "English": {
        "login": "🔐 Login",
        "register": "📝 Register",
        "welcome_back": "Welcome Back!",
        "username": "Username",
        "password": "Password",
        "email": "Email",
        "confirm_password": "Confirm Password",
        "login_button": "🔓 Login",
        "register_button": "📝 Register",
        "logout_button": "🚪 Logout",
        "practice": "Practice Your English",
        "analyze": "🔍 Analyze",
        "enter_sentence": "Enter your sentence:",
        "your_sentence": "Your Sentence:",
        "corrected": "Corrected Sentence:",
        "explanation": "Explanation",
        "tips": "Speaking Tips:",
        "quick_tips": "💡 Quick Tips",
        "session_history": "📋 Session History",
        "language_selection": "Select Your Language",
        "hindi": "🇮🇳 Hindi",
        "marathi": "🇮🇳 Marathi",
        "choose_language": "Choose your preferred language to continue:",
        "language_changed": "Language changed to:",
        "settings": "⚙️ Settings",
        "ai_model": "🤖 AI Model",
        "input_method": "🎙️ Input Method",
        "output": "🔊 Output",
        "enable_audio": "Enable audio feedback",
        "session_info": "📊 Session Info",
        "sentences_analyzed": "Sentences analyzed:",
        "text_input": "📝 Text Input",
        "microphone": "🎤 Microphone",
        "browser_audio": "🎙️ Browser Audio",
        "conversation": "💬 Conversation",
        "start_recording": "🎤 Start Recording",
        "captured": "✅ Captured:",
        "analyzing": "Analyzing...",
        "recording": "Recording...",
        "please_fill": "❌ Please fill in all fields",
        "error": "❌ Error:",
        "success": "✅ Success!",
        "great_job": "✅ Great job! Your sentence is correct!",
        "original": "Original",
        "user_profile": "👤 User Profile",
    },
    
    "Hindi": {
        "login": "🔐 लॉगिन",
        "register": "📝 रजिस्टर करें",
        "welcome_back": "स्वागत है!",
        "username": "उपयोगकर्ता नाम",
        "password": "पासवर्ड",
        "email": "ईमेल",
        "confirm_password": "पासवर्ड की पुष्टि करें",
        "login_button": "🔓 लॉगिन करें",
        "register_button": "📝 रजिस्टर करें",
        "logout_button": "🚪 लॉगआउट",
        "practice": "अपनी अंग्रेजी का अभ्यास करें",
        "analyze": "🔍 विश्लेषण करें",
        "enter_sentence": "अपना वाक्य दर्ज करें:",
        "your_sentence": "आपका वाक्य:",
        "corrected": "सुधरा हुआ वाक्य:",
        "explanation": "व्याख्या",
        "tips": "बोलने के सुझाव:",
        "quick_tips": "💡 तुरंत सुझाव",
        "session_history": "📋 सत्र का इतिहास",
        "language_selection": "भाषा चुनें",
        "hindi": "🇮🇳 हिंदी",
        "marathi": "🇮🇳 मराठी",
        "choose_language": "जारी रखने के लिए अपनी पसंदीदा भाषा चुनें:",
        "language_changed": "भाषा बदल गई:",
        "settings": "⚙️ सेटिंग्स",
        "ai_model": "🤖 एआई मॉडल",
        "input_method": "🎙️ इनपुट विधि",
        "output": "🔊 आउटपुट",
        "enable_audio": "ऑडियो प्रतिक्रिया सक्षम करें",
        "session_info": "📊 सत्र की जानकारी",
        "sentences_analyzed": "विश्लेषण किए गए वाक्य:",
        "text_input": "📝 पाठ इनपुट",
        "microphone": "🎤 माइक्रोफोन",
        "browser_audio": "🎙️ ब्राउज़र ऑडियो",
        "conversation": "💬 बातचीत",
        "start_recording": "🎤 रिकॉर्डिंग शुरू करें",
        "captured": "✅ कैप्चर किया गया:",
        "analyzing": "विश्लेषण किया जा रहा है...",
        "recording": "रिकॉर्डिंग...",
        "please_fill": "❌ कृपया सभी फ़ील्ड भरें",
        "error": "❌ त्रुटि:",
        "success": "✅ सफल!",
        "great_job": "✅ बहुत अच्छा! आपका वाक्य सही है!",
        "original": "मूल",
        "user_profile": "👤 उपयोगकर्ता प्रोफ़ाइल",
    },
    
    "Marathi": {
        "login": "🔐 लॉगिन",
        "register": "📝 नोंदणी करा",
        "welcome_back": "स्वागतम!",
        "username": "वापरकर्ता नाव",
        "password": "पासवर्ड",
        "email": "ईमेल",
        "confirm_password": "पासवर्डची पुष्टी करा",
        "login_button": "🔓 लॉगिन करा",
        "register_button": "📝 नोंदणी करा",
        "logout_button": "🚪 लॉगआउट",
        "practice": "आपल्या इंग्रजीचा सराव करा",
        "analyze": "🔍 विश्लेषण करा",
        "enter_sentence": "आपला वाक्य प्रविष्ट करा:",
        "your_sentence": "आपला वाक्य:",
        "corrected": "सुधारलेला वाक्य:",
        "explanation": "स्पष्टीकरण",
        "tips": "बोलण्याच्या सुचना:",
        "quick_tips": "💡 द्रुत सुचना",
        "session_history": "📋 सत्र इतिहास",
        "language_selection": "भाषा निवडा",
        "hindi": "🇮🇳 हिंदी",
        "marathi": "🇮🇳 मराठी",
        "choose_language": "सुरू ठेवण्यासाठी आपनी पसंतीची भाषा निवडा:",
        "language_changed": "भाषा बदलली:",
        "settings": "⚙️ सेटिंग्ज",
        "ai_model": "🤖 AI मॉडेल",
        "input_method": "🎙️ इनपुट पद्धत",
        "output": "🔊 आउटपुट",
        "enable_audio": "ऑडियो प्रतिक्रिया सक्षम करा",
        "session_info": "📊 सत्र माहिती",
        "sentences_analyzed": "विश्लेषण केलेले वाक्य:",
        "text_input": "📝 मजकूर इनपुट",
        "microphone": "🎤 मायक्रोफोन",
        "browser_audio": "🎙️ ब्राउজर ऑडियो",
        "conversation": "💬 संभाषण",
        "start_recording": "🎤 रेकॉर्डिंग सुरू करा",
        "captured": "✅ कॅप्चर केले:",
        "analyzing": "विश्लेषण सुरू आहे...",
        "recording": "रेकॉर्डिंग...",
        "please_fill": "❌ कृपया सर्व क्षेत्र भरा",
        "error": "❌ त्रुटी:",
        "success": "✅ यश!",
        "great_job": "✅ बहुतेक छान! आपला वाक्य सही आहे!",
        "original": "मूळ",
        "user_profile": "👤 वापरकर्ता प्रोफाइल",
    }
}

def get_text(key: str, language: str = "English") -> str:
    """Get translated text for a key in the specified language."""
    if language not in TRANSLATIONS:
        language = "English"
    
    return TRANSLATIONS[language].get(key, TRANSLATIONS["English"].get(key, key))

def get_language_name(lang_code: str) -> str:
    """Get the full language name from code."""
    lang_map = {
        "hindi": "Hindi",
        "marathi": "Marathi",
        "english": "English"
    }
    return lang_map.get(lang_code.lower(), "English")
